Далее в хронологическом порядке будет список моих статей с кратким вступлением.

* [[https://zepp.github.io/pages/totp.html][Чем полезен TOTP для обычного человека]]

В этой краткой статье я хочу рассказать, чем может быть полезен и удобен TOTP для обычного человека. Это не разбор стандарта с технической точки зрения и тут будет минимум терминов. Опираясь на ряд новостей и информацию из открытых источников, хотелось бы подсветить ряд очевидных проблем, которые возникают, если использовать устаревшие подходы.

* [[https://zepp.github.io/pages/jsr-310-abp.html][Работа с датой и временем при разработке под Android]]

В данной статье хотелось бы подробно рассмотреть, как работать с датой и временем при разработке приложений под Android. Статья будет полезна в первую очередь для мобильных разработчиков, но и, в некоторой степени, для начинающих backend-разработчиков. Всё написанное ниже актуально для тех случаев, когда система в целом рассчитана на работу в разных часовых поясах и события, соответственно, могут происходить в разных географических регионах. Это подразумевает, что в приложение реализованы сценарии, где осуществляется фиксация времени события, ввод даты и времени или просто есть сущности, обладающие такими атрибутами, как время создания и модификации. Сразу оговорюсь, что в статье не рассматриваются тонкости чем GMT отличается от UTC, или почему год не всегда содержит одинаковое количество секунд.

* [[https://zepp.github.io/pages/choco-emacs.html][Установка Emacs на Windows]]

Данная статья представляет собой инструкцию, в которой описывается установка и донастройка Emacs под Windows.

Основные сценарии использования:
+ ведение заметок и управление командой проекта при помощи [[https://orgmode.org/][Org-mode]];
+ написание статей и отчётов (возможен последующий перенос на wiki);
+ работа с git-репозиториями, содержащими исходный код проекта (ревью кода, поддержка feature-веток и так далее).
